import random
import oracledb
import time


sentences = [
    "The quick brown for jumps over the lazy dog",
    "Python is a powerful programming language",
    "Practice makes perfect every single day",
    "Oracle database stores data reliably",
    "Typing speed improves with daily practice",
]

conn = oracledb.connect(user="python_user",password="54321",dsn="localhost/xe")
cursor = conn.cursor()

# 테이블 생성
try:
    sql = """create table typing_records(
    record_id number(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elapsed varchar2(20) not null,
    accuracy varchar2(20) not null,
    regdate date default sysdate 
    )
    """
    cursor.execute(sql)
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955:
        print(error_obj.message)
    else:
        raise

# sentences 문장 중 임의의 문장을 출제후 사용자가 타이핑하는 시간을 잰 후 저장
# 정확도 계산
# 걸린시간, 정확도율, 날짜

# 임의의 문장 선택
# target = random.sample(sentences, k=1)

# 무작위로 하나 추출
target = random.choices(sentences)

print("아래 문장을 그대로 입력하세요:")
print(target)
input("준비되면 Enter를 누르세요...")

start = time.time()
typed = input()
end = time.time()

# 걸린시간
elapsed = format(end-start, ".3f")

# 정확도 계산
# zip() : 길이가 다르면 짧은 쪽 기준
# correct_chars = 0
# for a,b in zip(target,typed):
#     if a == b:
#         correct_chars += 1

# 정확한 문자 개수
correct_chars = sum(1 for a,b in zip(target,typed) if a == b)
# 정확도
accuracy = correct_chars / len(target) * 100
accuracy = format(accuracy, ".1f")

# 삽입
sql = "insert into typing_records(elapsed,accuracy) values(:1,:2)"
cursor.execute(sql,(elapsed,accuracy))
conn.commit()

cursor.close()
conn.close()